#!/bin/bash
echo "This will trigger a Cloud Run redeploy to pick up new IAM permissions"
echo ""
echo "Run this command in your terminal:"
echo ""
echo "gcloud run services update aviation-intelligence-api \\"
echo "  --region=us-central1 \\"
echo "  --update-env-vars=\"LAST_DEPLOY=\$(date +%s)\""
echo ""
echo "Or simply push a small change to trigger automatic deployment:"
echo ""
echo "cd aviation-intelligence-api"
echo "echo '# Trigger redeploy' >> README.md"
echo "git add README.md"
echo "git commit -m 'Trigger redeploy for IAM permissions'"
echo "git push"
