"""
News Article Model
Defines the data structure and validation for aviation news articles
"""

from dataclasses import dataclass, asdict
from datetime import datetime
from typing import List, Dict, Any, Optional
import hashlib

@dataclass
class NewsArticle:
    """
    Aviation news article data model for Firestore storage
    
    Attributes:
        source: Source identifier (e.g., "flightglobal_rss", "newsapi", "sec_edgar")
        source_url: Original article URL (used for deduplication)
        title: Article headline
        summary: Article summary or first ~500 chars of content
        content: Full text content if available
        published_at: Original publication datetime
        ingested_at: When we pulled the article
        tags: Categorization tags (leasing, mro, fleet, orders, bankruptcy, etc.)
        entities: Extracted entities (placeholder for future enrichment)
        raw_payload: Original API/RSS response for reprocessing
        id: Optional document ID (auto-generated by Firestore if not provided)
    """
    
    source: str
    source_url: str
    title: str
    summary: str
    content: str
    published_at: datetime
    ingested_at: datetime
    tags: List[str]
    entities: List[Dict[str, Any]]
    raw_payload: Dict[str, Any]
    id: Optional[str] = None
    ai_summary: Optional[str] = None          # AI-generated 100-200 word summary
    impact_statement: Optional[str] = None    # One sentence impact analysis
    
    def __post_init__(self):
        """Post-initialization processing"""
        # Ensure ingested_at is set
        if not self.ingested_at:
            self.ingested_at = datetime.utcnow()
        
        # Generate a consistent ID based on source_url if not provided
        if not self.id and self.source_url:
            self.id = self.generate_id()
    
    def generate_id(self) -> str:
        """Generate a consistent ID based on source_url"""
        return hashlib.md5(self.source_url.encode('utf-8')).hexdigest()
    
    def to_firestore_dict(self) -> Dict[str, Any]:
        """Convert to Firestore-compatible dictionary"""
        data = asdict(self)
        
        # Convert datetime objects to Firestore timestamps
        if isinstance(data['published_at'], datetime):
            data['published_at'] = data['published_at']
        if isinstance(data['ingested_at'], datetime):
            data['ingested_at'] = data['ingested_at']
        
        # Remove the id field for Firestore document creation
        if 'id' in data and data['id']:
            data.pop('id')
        
        return data
    
    @classmethod
    def from_firestore_dict(cls, doc_id: str, data: Dict[str, Any]) -> 'NewsArticle':
        """Create NewsArticle from Firestore document data"""
        # Handle Firestore timestamp conversion for published_at
        if 'published_at' in data:
            if hasattr(data['published_at'], 'timestamp'):
                # Firestore timestamp object
                data['published_at'] = datetime.fromtimestamp(data['published_at'].timestamp())
            elif isinstance(data['published_at'], str):
                # String datetime - try multiple formats
                try:
                    # Handle timezone-aware format: "2026-01-28 18:18:01+00:00"
                    if '+' in data['published_at'] or 'Z' in data['published_at']:
                        from dateutil.parser import parse
                        data['published_at'] = parse(data['published_at']).replace(tzinfo=None)
                    else:
                        # Handle basic format: "2026-01-28 18:18:01"
                        data['published_at'] = datetime.strptime(data['published_at'], '%Y-%m-%d %H:%M:%S')
                except Exception as e:
                    # Fallback - use current time if parsing fails
                    data['published_at'] = datetime.utcnow()
                    print(f"Warning: Failed to parse published_at for {doc_id}: {e}")
            elif isinstance(data['published_at'], datetime):
                # Already a datetime object
                pass
            else:
                # Unknown format - use current time
                data['published_at'] = datetime.utcnow()
        
        # Handle Firestore timestamp conversion for ingested_at
        if 'ingested_at' in data:
            if hasattr(data['ingested_at'], 'timestamp'):
                # Firestore timestamp object
                data['ingested_at'] = datetime.fromtimestamp(data['ingested_at'].timestamp())
            elif isinstance(data['ingested_at'], str):
                # String datetime
                try:
                    if '+' in data['ingested_at'] or 'Z' in data['ingested_at']:
                        from dateutil.parser import parse
                        data['ingested_at'] = parse(data['ingested_at']).replace(tzinfo=None)
                    else:
                        data['ingested_at'] = datetime.strptime(data['ingested_at'], '%Y-%m-%d %H:%M:%S')
                except Exception as e:
                    data['ingested_at'] = datetime.utcnow()
                    print(f"Warning: Failed to parse ingested_at for {doc_id}: {e}")
            elif isinstance(data['ingested_at'], datetime):
                # Already a datetime object
                pass
            else:
                # Unknown format - use current time
                data['ingested_at'] = datetime.utcnow()
        
        # Add the document ID
        data['id'] = doc_id
        
        # Filter out any extra fields that aren't part of NewsArticle model
        # This handles cases where Firestore has extra fields like 'source_type'
        valid_fields = {
            'source', 'source_url', 'title', 'summary', 'content',
            'published_at', 'ingested_at', 'tags', 'entities', 'raw_payload', 'id',
            'ai_summary', 'impact_statement'
        }
        filtered_data = {k: v for k, v in data.items() if k in valid_fields}
        
        # Ensure required fields have defaults if missing
        defaults = {
            'tags': [],
            'entities': [],
            'raw_payload': {},
            'summary': '',
            'content': '',
            'ai_summary': None,
            'impact_statement': None
        }
        
        for field, default_value in defaults.items():
            if field not in filtered_data:
                filtered_data[field] = default_value
        
        return cls(**filtered_data)
    
    def validate(self) -> List[str]:
        """
        Validate article data and return list of validation errors
        
        Returns:
            List of validation error messages (empty if valid)
        """
        errors = []
        
        if not self.source:
            errors.append("Source is required")
        
        if not self.source_url:
            errors.append("Source URL is required")
        
        if not self.title or len(self.title.strip()) == 0:
            errors.append("Title is required")
        
        if len(self.title) > 500:
            errors.append("Title too long (max 500 characters)")
        
        if len(self.summary) > 1000:
            errors.append("Summary too long (max 1000 characters)")
        
        if not self.published_at:
            errors.append("Published date is required")
        
        if self.published_at > datetime.utcnow():
            errors.append("Published date cannot be in the future")
        
        return errors
    
    def is_valid(self) -> bool:
        """Check if article data is valid"""
        return len(self.validate()) == 0
    
    def add_tags(self, new_tags: List[str]) -> None:
        """Add tags to the article, avoiding duplicates"""
        current_tags = set(self.tags)
        for tag in new_tags:
            if tag.lower() not in [t.lower() for t in current_tags]:
                self.tags.append(tag.lower())
    
    def auto_tag(self) -> None:
        """
        Automatically tag article based on content analysis
        This is a simple keyword-based tagging system
        """
        content_lower = f"{self.title} {self.summary} {self.content}".lower()
        
        # Define tag keywords
        tag_keywords = {
            'aircraft_leasing': ['aircraft leasing', 'lease', 'lessor', 'lessee', 'aercap', 'air lease corp'],
            'fleet_orders': ['aircraft order', 'delivery', 'airbus', 'boeing', 'fleet expansion'],
            'mro': ['maintenance', 'repair', 'overhaul', 'mro', 'aircraft maintenance'],
            'bankruptcy': ['bankruptcy', 'chapter 11', 'liquidation', 'financial distress'],
            'mergers_acquisitions': ['merger', 'acquisition', 'takeover', 'consolidation'],
            'fuel_costs': ['fuel cost', 'jet fuel', 'oil price', 'fuel hedging'],
            'regulatory': ['faa', 'easa', 'regulatory', 'compliance', 'certification'],
            'sustainability': ['sustainable aviation fuel', 'carbon neutral', 'emissions', 'green aviation'],
            'travel_demand': ['passenger demand', 'load factor', 'travel trends', 'booking'],

            # Risk-specific tags for weekly outlook
            'operational_risk': ['atc', 'air traffic control', 'delay', 'disruption', 'shortage',
                               'weather', 'capacity constraint', 'production delay', 'strike',
                               'pilot shortage', 'staffing', 'operational issue'],
            'financial_risk': ['fuel cost pressure', 'credit spread', 'debt', 'bankruptcy risk',
                             'liquidity', 'earnings miss', 'financial loss', 'cost pressure',
                             'revenue decline', 'cash flow'],
        }
        
        # Check content against keywords
        auto_tags = []
        for tag, keywords in tag_keywords.items():
            if any(keyword in content_lower for keyword in keywords):
                auto_tags.append(tag)
        
        # Add auto-generated tags
        self.add_tags(auto_tags)


# Aviation industry source configurations
AVIATION_SOURCES = {
    'flightglobal_rss': {
        'name': 'FlightGlobal',
        'type': 'rss',
        'url': 'https://www.flightglobal.com/rss',
        'active': True
    },
    'aviation_week_rss': {
        'name': 'Aviation Week',
        'type': 'rss', 
        'url': 'https://aviationweek.com/rss.xml',
        'active': True
    },
    'simple_flying_rss': {
        'name': 'Simple Flying',
        'type': 'rss',
        'url': 'https://simpleflying.com/feed/',
        'active': True
    },
    'reuters_aviation_rss': {
        'name': 'Reuters Business Aviation',
        'type': 'rss',
        'url': 'https://www.reutersagency.com/feed/?best-topics=business&post_type=best',
        'active': True
    },
    'air_lease_corp_rss': {
        'name': 'Air Lease Corp News',
        'type': 'rss',
        'url': 'https://www.airleasecorp.com/rss/news',
        'active': True
    },
    'newsapi': {
        'name': 'NewsAPI Aviation',
        'type': 'api',
        'active': True
    },
    'sec_edgar': {
        'name': 'SEC EDGAR Filings',
        'type': 'api',
        'active': True
    }
}

# Target companies for SEC EDGAR monitoring
SEC_TARGET_COMPANIES = {
    # Aviation Finance Companies
    'AER': {
        'name': 'AerCap Holdings N.V.',
        'cik': '0001378789',
        'ticker': 'AER'
    },
    'AL': {
        'name': 'Air Lease Corporation',
        'cik': '0001503503',  
        'ticker': 'AL'
    },
    
    # Aerospace Manufacturers
    'BA': {
        'name': 'The Boeing Company',
        'cik': '0000012927',
        'ticker': 'BA'
    },
    'LMT': {
        'name': 'Lockheed Martin Corporation',
        'cik': '0000936468',
        'ticker': 'LMT'
    },
    'GD': {
        'name': 'General Dynamics Corporation',
        'cik': '0000040533',
        'ticker': 'GD'
    },
    'RTX': {
        'name': 'Raytheon Technologies Corporation',
        'cik': '0001047122',
        'ticker': 'RTX'
    },
    
    # Additional Major Aviation Companies
    'UAL': {
        'name': 'United Airlines Holdings, Inc.',
        'cik': '0000100517',
        'ticker': 'UAL'
    },
    'DAL': {
        'name': 'Delta Air Lines, Inc.',
        'cik': '0000027904',
        'ticker': 'DAL'
    },
    'AAL': {
        'name': 'American Airlines Group Inc.',
        'cik': '0000006201',
        'ticker': 'AAL'
    },
    'LUV': {
        'name': 'Southwest Airlines Co.',
        'cik': '0000092380',
        'ticker': 'LUV'
    }
}